version: 1
title: "DCTT Pipeline (Hard Pivot)"
subtitle: "Mechanistic-positive intervention with strict predictive gate"
layout:
  xlim: [0.0, 14.0]
  ylim: [0.0, 8.0]

stages:
  - id: stage0
    label: "Stage 0\nPreprocessing"
    detail: "extract embeddings"
    x: 1.3
    y: 5.4
    width: 2.2
    height: 1.3
    color: "#ECEFF3"

  - id: stage1
    label: "Stage 1\nOutlier Signals"
    detail: "mu_k, spread_q, LOF"
    x: 4.0
    y: 5.4
    width: 2.2
    height: 1.3
    color: "#D8EBFF"

  - id: stage2
    label: "Stage 2\nSpectral Geometry"
    detail: "cond, PR, logdet, dim95"
    x: 6.7
    y: 5.4
    width: 2.2
    height: 1.3
    color: "#DDF2D8"

  - id: stage3
    label: "Stage 3\nSeverity & Clusters"
    detail: "tiering + cluster selection"
    x: 9.4
    y: 5.4
    width: 2.2
    height: 1.3
    color: "#F8E7C9"

  - id: repair
    label: "Cluster Repair\nMechanistic Test"
    detail: "geometry improves vs placebo"
    x: 6.7
    y: 2.9
    width: 2.6
    height: 1.4
    color: "#EADCF9"

  - id: predictive
    label: "Predictive Gate\n(Strict)"
    detail: "real labels + confound alignment"
    x: 10.0
    y: 2.9
    width: 2.8
    height: 1.4
    color: "#F8DDE3"

edges:
  - from: stage0
    to: stage1
    style: solid
  - from: stage1
    to: stage2
    style: solid
  - from: stage2
    to: stage3
    style: solid
  - from: stage2
    to: repair
    style: solid
  - from: stage3
    to: predictive
    style: solid
  - from: repair
    to: predictive
    style: dashed

footer:
  text: "Dashed edge: hypothesis path evaluated under strict gate and retained as negative predictive evidence."
  x: 7.0
  y: 0.8
